# Generated by Django 3.1.8 on 2021-08-12 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='bid',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='starting_bid',
            field=models.FloatField(default=90.99),
            preserve_default=False,
        ),
    ]
