# Generated by Django 3.1.8 on 2021-08-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210814_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='bids',
            field=models.ManyToManyField(blank=True, related_name='bids_in_the_auction', to='auctions.Bid'),
        ),
    ]
